export default {
    Home: require('../assets/home.png'),
    user: require('../assets/PrIMG.png'),
    dashboard: require('../assets/Dash.png'),
    product: require('../assets/new-product.png'),
    service: require('../assets/service.png'),
    purchase: require('../assets/purchase.png'),
    client: require('../assets/client.png'),
    sale: require('../assets/sale.png'),
    dealer: require('../assets/dealer.png'),
    dailyTask: require('../assets/dailyTask.png'),
    productDispatch: require('../assets/productDispatch.png'),
    payments: require('../assets/payments.png'),
    employeeRegistration: require('../assets/employeeRegistration.png'),
    partyRegistration: require('../assets/partyRegistration.png'),
    manufacturing: require('../assets/manufacturing.png'),
    notification: require('../assets/notification.png'),
    setting: require('../assets/setting.png'),
    arrowsBack: require('../assets/arrowsBack.png'),
    coverBanner: require('../assets/coverBanner.jpg'),
    whats: require('../assets/whats.png'),
    gmail: require('../assets/gmail.png'),
    phone: require('../assets/phone.png'),
    receipt: require('../assets/receipt.png'),
    view: require('../assets/view.png'),
    delete: require('../assets/delete.png'),
}