import { Dimensions, StatusBar, StyleSheet } from "react-native";
import Colors from "./constants/color";
import Fonts from "./constants/fonts";
const { height } = Dimensions.get('window');
const { width } = Dimensions.get('window');


const styles = StyleSheet.create({
  loginContainer: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  loginHeading: {
    fontSize: 28,
    marginBottom: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  input: {
    marginBottom: 10,
    backgroundColor: "#ffffffff",
    width: '95%',
  },
  LoginForgotText: {
    textAlign: 'right',
    color: '#447bf3ff',
    marginBottom: 16,
  },
  LoginButton: {
    marginVertical: 10,
    backgroundColor: '#4d67a1ff',
    paddingVertical: 12,
    borderRadius: 5,
    borderWidth: 1,
  },
  LoginButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center'
  },
  LoginGoogleButton: {
    borderColor: '#db4437',
    marginTop: 10,
  },
  orText: {
    textAlign: 'center',
    marginVertical: 10,
    color: '#777',
  },
  registerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  registerText: {
    color: '#2e6ef7',
    fontWeight: '600',
  },
  scrollContainer: {
    flexGrow: 1,
    paddingTop: StatusBar.currentHeight || 40,
    paddingBottom: 20,
    paddingHorizontal: 20,
    backgroundColor: '#fff' // Or use from your MainStyle
  },
  GradientText: {
    fontSize: 30,
    color: '#fff'
  },
  FlexContainer: {
    backgroundColor: '#ffffff',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    height: '5%',

  },
  FlexItems: {
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    height: '70%',
    width: '45%',
    borderRadius: 25,
    borderColor: '#7f8378ff',
    borderWidth: 1,
  },
  FlexText: {
    color: '#7f8378ff',
  },

  card: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 15,
    margin: 10,
    elevation: 3, // Android shadow
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  partyName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    flex: 1,
  },
  tag: {
    backgroundColor: "#ffe6e6",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 15,
    marginRight: 10,
  },
  tagText: {
    fontSize: 12,
    color: "#ff4d4d",
    fontWeight: "bold",
  },
  date: {
    fontSize: 12,
    color: "#666",
  },
  bottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  rowLeft: {
    flexDirection: "row",
  },
  column: {
    marginRight: 30,
  },
  label: {
    fontSize: 13,
    color: "#666",
  },
  value: {
    fontSize: 15,
    fontWeight: "600",
    color: "#000",
  },
  rowRight: {
    flexDirection: "row",
  },
  icon: {
    fontSize: 18,
    marginLeft: 15,
    color: "#444",
  },
  //  Item Screen CSS Starts

  itemBox: {
    backgroundColor: "#fff",
    padding: 20,
    margin: 10,
    borderRadius: 10,
    elevation: 2,
  },
  floatingBtn: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    alignItems: "center",
  },
  btn: {
    backgroundColor: "#66BB6A",
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 30,
    elevation: 5,
  },
  btnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  //  Item Screen CSS Ends
  card: {
    backgroundColor: "#fff",
    padding: 12,
    marginVertical: 8,
    marginHorizontal: 12,
    borderRadius: 8,
    elevation: 3, // Android shadow
    shadowColor: "#000", // iOS shadow
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  productName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#4CAF50",
  },
  batch: {
    fontSize: 14,
    color: "#7f8378ff",
  },
  label: {
    fontSize: 14,
    color: "#333",
  },
  cost: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#e91e63",
  },
  remarks: {
    fontSize: 12,
    color: "#7f8378ff",
    fontStyle: "italic",
  },
  ////////////////////
  itemBox: {
    backgroundColor: "#fff",
    padding: 15,
    marginBottom: 10,
    borderRadius: 8,
    elevation: 3,
  },
  floatingBtn: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#4CAF50",
    padding: 15,
    borderRadius: 50,
    elevation: 5,
  },
  btnText: {
    color: "#fff",
    fontWeight: "bold",
  },
  submitBtn: {
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12,
    width: '50%',
  },
  btnBody: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    position: 'absolute',
    bottom: 10,
    alignSelf: 'center',
    backgroundColor: '#fff',
  },
  cancelBtn: {
    backgroundColor: "#f44336",
    height: 50,
    width: '50%',
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4, // Android shadow
  },
  submitBtn: {
    backgroundColor: "#4CAF50",
    height: 50,
    width: '50%',
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  dashTopBox: { display: 'flex', flexDirection: 'row', gap: 10, padding: 20, },
  dashBoxes: { flexDirection: 'column', flex: 1, backgroundColor: Colors.light, justifyContent: 'center', alignItems: 'center', borderRadius: 8, height: 60 },
  dashTextOne: { fontFamily: Fonts.boldItalic, fontSize: Fonts.sizes.regular, fontWeight: Fonts.weights.bold, color: Colors.primary },
  dashTextTwo: { fontFamily: Fonts.boldItalic, fontSize: Fonts.sizes.regular, fontWeight: Fonts.weights.bold, color: Colors.danger },
  // CardText: { fontSize: 24, fontWeight: 'bold', color: Colors.text, textAlign: 'center' },
  purchaseButton: {
    position: 'absolute',
    top: 15,
    right: 20,
    backgroundColor: "#82AB7D",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    borderWidth: 1,
    borderColor: '#fff'
  },
  purchaseButtonText: {
    color: '#fff',
    fontFamily: Fonts.large,
    fontWeight: 'bold',
  },
  cardHeading: { display: 'flex', paddingTop: 1, justifyContent: 'center', alignItems: 'center', },
  cardButton: { borderRadius: 10, backgroundColor: Colors.sweetGreen, width: '90%', justifyContent: 'center', alignItems: 'center', height: 60, paddingHorizontal: 10, borderColor: '#f2f2f2', borderWidth: 2 },
  cardText: { fontFamily: Fonts.bold, fontSize: 20, fontWeight: '900', color: Colors.dark },
  bottomButtonBody: { flexDirection: "row", justifyContent: "space-around", width: "100%", position: 'fix', bottom: 0, backgroundColor: Colors.background, paddingVertical: 10 },
  bottomButtonCancel: { backgroundColor: "#f44336", height: 50, width: '45%', justifyContent: "center", alignItems: "center", shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 3, elevation: 4, borderRadius: 10 },
  bottomButtonColumnSubmit: { backgroundColor: "#4CAF50", height: 50, width: '45%', justifyContent: "center", alignItems: "center", shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 3, elevation: 4, borderRadius: 10 },
  bottomButtonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
  quickAccessCard: {
    width: '48%',
    borderRadius: 12,
    marginBottom: 15,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    overflow: 'hidden',
    // height: 'auto'
  },
  QuickAcessCardGradient: {
    flex: 1,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardText: { color: '#0a0a0aff', fontSize: 16, fontWeight: 'bold', textAlign: 'center' },

  HomecardText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.primary,
    marginTop: 10
  },
  homeImagesCss: { height: '33%', width: '25%', alignSelf: 'flex-end' },
  homeTopCard: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', width: '100%', height: 190 },
  homeCardBodyLeft: { flexDirection: 'column', justifyContent: 'space-around', alignItems: 'flex-start', backgroundColor: '#ffffff', height: 190, width: '45%', borderRadius: 10, borderColor: '#e0e0e0', borderWidth: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.15, shadowRadius: 6, elevation: 4, paddingHorizontal: 10, gap: 50 },
  homeCardBodyRight: { flexDirection: 'column', justifyContent: 'center', alignItems: 'center', height: 190, width: '45%' },
  // homeCardLeft: { justifyContent: 'space-around',  backgroundColor: pressed ? Colors.sweetGreen : '#ffffff', width: '100%', height: '48%', borderRadius: 15, paddingHorizontal: 10, },
  homeMenuBody: { backgroundColor: '#ffffff', width: '100%', height: 140, flex: 1, flexDirection: "row", justifyContent: 'space-around', alignItems: 'center', borderRadius: 10, borderColor: Colors.border, borderWidth: 1.5, shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.15, shadowRadius: 6, elevation: 1, },

  menuColumnCss: {
    backgroundColor: Colors.textOrCardBackground,
    width: 60,
    height: 60,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  homeCardInnerBody: { alignItems: 'center', width: '25%', },
  menuCardHeading: { color: Colors.primary, fontSize: 15, fontWeight: '500', marginTop: 10 },
  menuCardSubHeading: { color: Colors.primary, fontSize: 15, fontWeight: '500' },
  slide: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // height: height * 0.3,
    backgroundColor: '#4CAF50',
    borderRadius: 15,
    margin: 15,
    elevation: 5,
  },
  text: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  dot: {
    backgroundColor: 'grey',
    width: 8,
    height: 8,
    borderRadius: 4,
    margin: 3,
  },
  activeDot: {
    backgroundColor: '#ebf5ecff',
    width: 10,
    height: 10,
    borderRadius: 5,
    margin: 3,
  },
  CarouselContainer: {
    height: 220,
  },
  card: {
    width: width,
    height: 200,
    borderRadius: 15,
    marginHorizontal: 5,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  image: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    borderRadius: 10,
  },
  text: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 15,
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#4CAF50",
    alignSelf: "flex-start",
    marginVertical: 10,
    marginLeft: 15,
  },
  SectionRow: {
    flexDirection: "row",
    width: "100%",
    paddingHorizontal: 10,
  },
  submitContainer: {
    marginTop: 20,
    paddingHorizontal: 10,
  },
  submitButton: {
    backgroundColor: "#1976D2",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  submitText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  listCardBody: { flexDirection: 'row', justifyContent: 'space-between' },
  listStatus: {
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '600',
    overflow: 'hidden',
  },
  subcardId: {
    fontSize: 13,
    color: '#6b7280',
    fontWeight: '500',
  },
  cardMiddle: {
    marginBottom: 15,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  subcardText: {
    fontSize: 13,
    color: '#6b7280',
  },
  listCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  moreInfo: {
    fontSize: 13,
    fontWeight: '600',
    color: '#2563eb',
  },
  cardImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
  },
  infocardImage: {
    width: 30,
    height: 30,
    // borderRadius: 30,
    backgroundColor: '#f5f5f5',
    padding: 8,
  },
  cardDealerBody: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 15,
    marginVertical: 8,
    marginHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  listCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  backheader: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 10 },
  cardInfoHeader: { fontSize: 20, color: Colors.primary },
  infoPhotoContainer: { backgroundColor: '#fff', marginBottom: 60, justifyContent: 'center', alignContent: 'center', alignItems: 'center' },
  coverPhoto: {
    width: '104%',
    height: 180,
    top: 10,

  },
  profileContainer: {
    position: 'absolute',
    top: 130, // overlap position
    left: 20,
    borderWidth: 3,
    borderColor: '#fff',
    borderRadius: 60,
    elevation: 5, // shadow for Android
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },
  infocard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 15,
    marginTop: 50, // to push down after profile image
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
  },
  clientName: {
    fontSize: 20,
    fontWeight: "bold",
    color: Colors.primary,
    textAlign: "center",
  },
  clientSub: {
    fontSize: 14,
    color: "#7f8378ff",
    textAlign: "center",
    marginBottom: 10,
  },
  divider: {
    height: 1,
    backgroundColor: "#e0e0e0",
    marginVertical: 10,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 4,
  },
  label: {
    fontSize: 15,
    fontWeight: "600",
    color: "#555",
  },
  value: {
    fontSize: 15,
    color: "#333",
  },
  socialBody: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 20,
    paddingVertical: 10,
    backgroundColor: "#f3efefff",
    borderRadius: 12,
    marginHorizontal: 20
  },
  deletebutton: {
    backgroundColor: "#D32F2F", // danger red
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5, // Android shadow
    width: '90%',
    alignSelf: 'center'
  },
  deletetext: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  purchaseCardBody: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginVertical: 5,
    width: '95%',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f2f2f2',
  },
  purchaseCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  status: {
    fontSize: 13,
    fontWeight: '700',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    overflow: 'hidden',
    textTransform: 'capitalize',
  },
  cardId: {
    fontSize: 13,
    color: '#7A7A7A',
    fontWeight: '500',
  },
  purchaseCardContent: {
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 8,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 4,
  },
  label: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  value: {
    fontSize: 14,
    color: '#222',
    fontWeight: '600',
  },
  dots: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#555',
  },
  overlay: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingTop: 80,
    paddingRight: 15,
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  menuBox: {
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingVertical: 5,
    width: 120,
    elevation: 6,
  },


})

export default styles;